version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./
    image: moneyforward-slack-bot:latest
    environment:
      - SLACK_SIGNING_SECRET
      - SLACK_BOT_TOKEN
      - MONEYFORWARD_MAIL_ADDRESS
      - MONEYFORWARD_PASSWORD
      - MONEYFORWARD_GROUP_DI
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
