name: Docker build & deploy

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVICE: moneyforward-slack-bot
  REGION: us-central1
  REPOSITORY: moneyforward-slack-bot
  IMAGE: moneyforward-slack-bot-image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true  # Set to true to authenticate the Cloud Run action

    - name: Authorize Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and Push Artifact Registry
      run: |-
        gcloud builds submit --config=cloudbuild.yaml \
          --substitutions=_REPOSITORY="${{ env.REPOSITORY }}",_IMAGE="${{ env.IMAGE }}" .

    - name: Deploy to Cloud Run
      id: deploy
      run: |-
        gcloud run deploy ${{ env.SERVICE }} \
          --image ${{env.REGION}}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }} \
          --platform managed \
          --region ${{env.REGION}} \
          --allow-unauthenticated \
          --memory 512Mi \
          --set-env-vars PROJECT_ID=${{ env.PROJECT_ID }}
          --set-env-vars SLACK_SIGNING_SECRET=${{ secrets.SLACK_SIGNING_SECRET }}
          --set-env-vars SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}
          --set-env-vars MONEYFORWARD_MAIL_ADDRESS=${{ secrets.MONEYFORWARD_MAIL_ADDRESS }}
          --set-env-vars MONEYFORWARD_PASSWORD=${{ secrets.MONEYFORWARD_PASSWORD }}
          --set-env-vars MONEYFORWARD_GROUP_ID=${{ secrets.MONEYFORWARD_GROUP_ID }}